name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      ACCOUNT: ${{ secrets.ACCOUNT }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DESCRIPTION: ${{ secrets.DESCRIPTION }}
      COUNTRY: ${{ secrets.COUNTRY }}
      KEY: ${{ secrets.KEY }}
      ADDRESS: ${{ secrets.ADDRESS }}
      CITY: ${{ secrets.CITY }}
      PROVINCE: ${{ secrets.PROVINCE }}
      LONGITUDE: ${{ secrets.LONGITUDE }}
      LATITUDE: ${{ secrets.LATITUDE }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Unit
      run: |
        go mod download
        go run main.go
        go test -v -run ^TestRemoteEnv$ towelong/mogu/test
        go test -v -run ^TestRemoteTime$ towelong/mogu/test
        go test -count=1 -v -run ^TestWeek$ towelong/mogu/test
        go test -count=1 -v -run ^TestWeekDiary$ towelong/mogu/test
