name: schedule-start

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    env:
      ACCOUNT: ${{ secrets.ACCOUNT }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DESCRIPTION: ${{ secrets.DESCRIPTION }}
      COUNTRY: ${{ secrets.COUNTRY }}
      KEY: ${{ secrets.KEY }}
      ADDRESS: ${{ secrets.ADDRESS }}
      CITY: ${{ secrets.CITY }}
      PROVINCE: ${{ secrets.PROVINCE }}
      LONGITUDE: ${{ secrets.LONGITUDE }}
      LATITUDE: ${{ secrets.LATITUDE }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Run App
        run: |
          go mod download
          go run main.go
